Refactor static library search paths
graalvm/mandrel pull request #136
Opened 2020-09-15 12:21 UTC by jerboaa

20.1 backport of https://github.com/oracle/graal/commit/d7b5904db656d1313d6462a0034818dfccbbb69b

This is in preparation for #125 and corresponding fix in upstream OpenJDK packaging in https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/pull/10

We should only merge close to the OpenJDK 11.0.9 release. The main difference to https://github.com/oracle/graal/commit/d7b5904db656d1313d6462a0034818dfccbbb69b are in `substratevm/mx.substratevm/mx_substratevm.py`

2020-09-15 12:31 UTC, jerboaa commented
Tests aren't expected to pass until AdoptOpenJDK/openjdk11-upstream-binaries#10 is merged and a first version of a vanilla build done.

2020-09-15 13:13 UTC, zakkak reviewed
Thanks Severin
LGTM

2020-10-09 08:54 UTC, jerboaa commented
This isn't going to pass CI until updated vanilla builds arrive which implement the static libs layout change. That isn't going to be happening until the OpenJDK 11.0.9 GA build around October 20.

2020-10-15 13:38 UTC, zakkak requested changes
As suggested by @jerboaa adding https://github.com/oracle/graal/commit/ece265a89e6cfa8cd5f10881891f73661f5cc04f to this PR will allow 20.1 to build with both 11.0.8-GA (plus 11.0.9-ea) and 11.0.9-GA (which will feature the new static libraries layout).

@jerboaa do you think we also need the following two?
* https://github.com/oracle/graal/commit/2a1945d6e36e2f7c1bdc5756f30d72c5332f4f89 (It's supposed to fix some issue when building with "older JDKs")
* https://github.com/oracle/graal/commit/9a1f46d9e6c149ed9720666a66f9e18a7baa4c3e (removes the warning the above commit adds ^^)

2020-10-15 18:10 UTC, jerboaa commented
> As suggested by @jerboaa adding [oracle@ece265a](https://github.com/oracle/graal/commit/ece265a89e6cfa8cd5f10881891f73661f5cc04f) to this PR will allow 20.1 to build with both 11.0.8-GA (plus 11.0.9-ea) and 11.0.9-GA (which will feature the new static libraries layout).

Yes, agreed.

> @jerboaa do you think we also need the following two?
> 
>     * [oracle@2a1945d](https://github.com/oracle/graal/commit/2a1945d6e36e2f7c1bdc5756f30d72c5332f4f89) (It's supposed to fix some issue when building with "older JDKs")
> 
>     * [oracle@9a1f46d](https://github.com/oracle/graal/commit/9a1f46d9e6c149ed9720666a66f9e18a7baa4c3e) (removes the warning the above commit adds ^^)

@zakkak No. I'd not backport them for no good reason. We should try to keep churn to the 20.1 branch as little as possible.

2020-10-19 16:15 UTC, jerboaa commented
This now also adds a backport of https://github.com/oracle/graal/commit/ece265a89e6cfa8cd5f10881891f73661f5cc04f

It should therefore be backwards compatible and the CI build should work.

@zakkak Thoughts?

2020-10-19 16:18 UTC, zakkak approved these changes
LGTM, let's see what the CI has to say as well :)

Thanks @jerboaa

2020-10-19 23:46 UTC, merged

2020-10-20 08:40 UTC, jerboaa commented
Thanks for the merge.