Build nightly with the JDK 23 release branch (24.1)
graalvm/mandrel pull request #750
Opened 2024-06-25 08:17 UTC by jerboaa

Partial fix for #749. This switches nightly builds to use the new `mandrel/24.1` branch (currently broken). CI builds for 24.2 (JDK 24) to follow once https://github.com/adoptium/api.adoptium.net/issues/1077 is resolved.

2024-06-25 09:43 UTC, jerboaa commented
Mandrel build fails because we need a backport of https://github.com/oracle/graal/pull/9078 to be able to build with JDK 23+26 and better. PR for that in progress.

2024-06-25 10:34 UTC, jerboaa commented
@zakkak Not sure if this is the right approach. Maybe we should keep nightly on graal/master and change to JDK 24? And then possibly adding JDK 23 based builds test to the weekly schedule. Thoughts?

2024-06-26 15:30 UTC, zakkak requested changes
> @zakkak Not sure if this is the right approach. Maybe we should keep nightly on graal/master and change to JDK 24? And then possibly adding JDK 23 based builds test to the weekly schedule. Thoughts?

Yes, that's the way we usually do it as we don't expect many changes on the release branch.

So we need to:
1. move the 23-based builds to the weekly pipeline
2. Create new issues for CI reporting and use them in the corresponding jobs
3. update the jdk version in the nightly pipeline

2024-06-26 15:30 UTC, zakkak commented on .github/workflows/nightly.yml
>        jdk: "latest/ea"
You would need to change this to 23 as well.

2024-06-26 16:17 UTC, jerboaa commented
> > @zakkak Not sure if this is the right approach. Maybe we should keep nightly on graal/master and change to JDK 24? And then possibly adding JDK 23 based builds test to the weekly schedule. Thoughts?
> 
> Yes, that's the way we usually do it as we don't expect many changes on the release branch.

OK.

>     2. Create new issues for CI reporting (using @mandrel-bot) and use them in the corresponding jobs

Any guidance as to how to do that?

2024-06-26 16:33 UTC, jerboaa commented
Withdrawing this PR as we'll fix this with a different approach.

2024-06-26 16:33 UTC, closed without merging

2024-06-26 18:32 UTC, zakkak commented
> Any guidance as to how to do that?

I open a new private window in firefox and login using the mandrel-bot credentials. You should have access to these through our shared vault (if not let me know in private).