[24.1] Backport: Updated JFR substitutions from [GR-54877]
graalvm/mandrel pull request #764
Opened 2024-07-03 16:43 UTC by roberttoyonaga

(cherry picked from commit fbc44e955f24be7de1c6364fc3256273c0763073)

Related issue: https://github.com/graalvm/mandrel/issues/763

[A change to OpenJDK JFR](https://bugs.openjdk.org/browse/JDK-8304732) was introduced in JDK 24 and later backported to JDK23+29. The Mandrel GHAs are using JDK23+29 so builds that include JFR will fail due to out of date substitutions.

2024-07-03 17:52 UTC, roberttoyonaga commented
Failing GHAs:
- `Mandrel-Quarkus tests / Q main M 24.1 EA / Q IT Data6 ` Looks unrelated. Seems related to: `io.quarkus.it.hibernate.search.orm.elasticsearch.coordination.outboxpolling.HibernateSearchOutboxPollingInGraalIT.testSearch`.
- `Mandrel-Quarkus tests / Q main M 24.1 EA / Q IT Messaging1` Also seems unrelated. Related to an authentication failure `io.quarkus.it.kafka.KafkaOauthIT.test`
- `Mandrel-Quarkus tests / Q main M 24.1 EA / Q Mandrel IT` Will be fixed once https://github.com/graalvm/mandrel/pull/762 is merged

2024-07-03 18:35 UTC, zakkak approved these changes
LGTM other than the references to JDK 24 source code. @roberttoyonaga could you please adapt them accordingly? Thank you

2024-07-03 18:35 UTC, zakkak commented on substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/PosixPlatformTimeUtils.java
> +    @BasedOnJDKFile("https://github.com/openjdk/jdk/blob/jdk-24+3/src/hotspot/os/posix/os_posix.cpp#L1409-L1415")
@roberttoyonaga can you please adapt this to reference the corresponding lines of code in jdk-23+?

2024-07-03 18:35 UTC, zakkak commented on substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/util/PlatformTimeUtils.java
> +    @BasedOnJDKFile("https://github.com/openjdk/jdk/blob/jdk-24+3/src/hotspot/share/jfr/recorder/repository/jfrChunk.cpp#L38-L54")
and here

2024-07-03 18:35 UTC, zakkak requested changes
LGTM other than the references to JDK 24 source code. @roberttoyonaga could you please adapt them accordingly? Thank you

2024-07-03 19:52 UTC, roberttoyonaga commented
> LGTM other than the references to JDK 24 source code. @roberttoyonaga could you please adapt them accordingly? Thank you

yes, thanks for spotting that. Done!

2024-07-04 08:15 UTC, jerboaa commented
CI failures are known:

* [Q main M 23 latest / Q IT Messaging1](https://github.com/graalvm/mandrel/actions/runs/9783984128/job/27014828796?pr=764): quarkus-integration-test-kafka-oauth-keycloak native integration failure due to: https://github.com/quarkusio/quarkus/issues/39634.
* [Q main M 23 latest / Q IT Data6](https://github.com/graalvm/mandrel/actions/runs/9783984128/job/27014828234?pr=764): quarkus-integration-test-hibernate-search-orm-elasticsearch-outbox-polling fails due to a version parsing issue of 23-beta as reported in https://github.com/quarkusio/quarkus/issues/39664 (caused by this upstream awaitability issue: https://github.com/awaitility/awaitility/issues/277). We see the same on 22-beta builds.
* [Q Mandrel IT](https://github.com/graalvm/mandrel/actions/runs/9783984128/job/27014826225?pr=764): Is caused by awt integration tests failing on JDK 23. See https://github.com/Karm/mandrel-integration-tests/issues/262

2024-07-04 08:18 UTC, jerboaa approved these changes

2024-07-04 08:19 UTC, zakkak approved these changes
Thank you @roberttoyonaga !

2024-07-04 08:19 UTC, merged

2024-07-17 12:05 UTC, zakkak commented
This backport was replaced by upstream https://github.com/oracle/graal/commit/27149a9b18a12eff1ae5983af16362a0bd191481